baseurl = "http://andy4thehuynh.github.io/"
title = "Jots of Code"
author = "Andy Huynh"

builddrafts = false
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
canonifyurls = true

pygmentsuseclasses = true
disqusShortname = "andy4thehuynh"
theme = "nietzsche"
