theme = "cocoa"
baseurl = "http://andy4thehuynh.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Andy Huynh"
title = "andy4thehuynh's blog"
pygmentsuseclasses = true
disqusShortname = "andy4thehuynh"
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Andy Huynh"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Digesting books, talks and meetups will land you a job like me!"
Email = "andy4thehuynh@gmail.com"
FaviconFile = "favicon.io"
GitHub = "https://github.com/andy4thehuynh"
HighlightJS = true
Initials = "ah" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
LinkedIn = "https://www.linkedin.com/in/andy-huynh-a9267922"
Twitter = "https://twitter.com/Andy4thehuynh"
ExtraCssFiles = [ "/css/override.css"  ] # In your `static/css`, add/remove files as necessary.

paginate = 10
